# pytorch_lightning==1.9.4
seed_everything: true
ckpt_path: null
wandb_ckpt_path: null
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      name: null
      project: WSI
      entity: gipmed
      mode: online
  devices: 1
  accelerator: gpu
model:
  model: resnet50
  num_classes: 2
  ckpt_path: null
  imagenet_pretrained: false
data:
  dataset: CAT
  target: ER
  val_fold: 1
  eval_on_train: false
  patches_per_slide_eval: 100
  min_tiles_eval: 100
  img_size: 256
  batch_size: 256
  num_workers: 8
  normalization: cat
